# Generated by Django 3.1.3 on 2022-06-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topdiez',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True)),
                ('genero', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('capitulos', models.TextField(blank=True)),
                ('duracion', models.TextField(blank=True)),
                ('temporadas', models.TextField(blank=True)),
                ('fecha', models.TextField(blank=True)),
            ],
        ),
    ]
